name: finance
channels:
  - pytorch
  - conda-forge
  - quantlib
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - adwaita-icon-theme=49.0=unix_0
  - aiofiles=25.1.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.6=pyhd8ed1ab_0
  - aiohttp=3.11.13=py312h998013c_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - anyio=4.9.0=pyh29332c3_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - applaunchservices=0.3.0=pyh534df25_4
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py312h024a12e_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - arviz=0.23.0=pyhcf101f3_0
  - asgi-csrf=0.11=pyhff2d567_0
  - asgiref=3.10.0=pyhd8ed1ab_0
  - astroid=3.3.9=py312h81bd7bf_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - asyncssh=2.20.0=pyhd8ed1ab_0
  - atk-1.0=2.38.0=hd03087b_2
  - atomicwrites=1.4.1=pyhd8ed1ab_1
  - attrs=25.1.0=pyh71513ae_0
  - autopep8=2.0.4=pyhd8ed1ab_0
  - aws-c-auth=0.9.0=hb5b73c5_15
  - aws-c-cal=0.9.2=h03444cf_0
  - aws-c-common=0.12.3=h5505292_0
  - aws-c-compression=0.3.1=hca07070_5
  - aws-c-event-stream=0.5.4=h40449bf_12
  - aws-c-http=0.10.2=hb5bd760_2
  - aws-c-io=0.20.1=hf355ecc_0
  - aws-c-mqtt=0.13.1=h923d298_3
  - aws-c-s3=0.8.1=h78ecdd8_3
  - aws-c-sdkutils=0.2.4=hca07070_0
  - aws-checksums=0.2.7=hca07070_1
  - aws-crt-cpp=0.32.8=ha2de2ec_6
  - aws-sdk-cpp=1.11.510=h8888cfc_10
  - azure-core-cpp=1.14.0=hd50102c_0
  - azure-identity-cpp=1.10.0=hc602bab_0
  - azure-storage-blobs-cpp=12.13.0=h7585a09_1
  - azure-storage-common-cpp=12.8.0=h9ca1f76_1
  - azure-storage-files-datalake-cpp=12.12.0=hcdd55da_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhd8ed1ab_1
  - beautifulsoup4=4.13.3=pyha770c72_0
  - binaryornot=0.4.4=pyhd8ed1ab_2
  - black=25.1.0=pyh866005b_0
  - blas=2.305=accelerate
  - blas-devel=3.11.0=5_h55bc449_accelerate
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blinker=1.9.0=pyhff2d567_0
  - boto3=1.38.40=pyhd8ed1ab_0
  - botocore=1.38.41=pyge310_1234567_0
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - brotli-python=1.1.0=py312hde4cb15_2
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.2=pyhd8ed1ab_0
  - cairo=1.18.4=h6a3b0d2_0
  - cctools_impl_osx-arm64=1030.6.3=llvm19_1_h8c76c84_3
  - cctools_osx-arm64=1030.6.3=llvm19_1_h6d92914_3
  - certifi=2023.11.17=pyhd8ed1ab_2
  - cffi=1.17.1=py312h0fad829_0
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - clang=19.1.7=default_hf9bcbb7_5
  - clang-19=19.1.7=default_h73dfc95_5
  - clang_impl_osx-arm64=19.1.7=h76e6a08_28
  - clang_osx-arm64=19.1.7=h07b0088_28
  - clangxx=19.1.7=default_h36137df_5
  - clangxx_impl_osx-arm64=19.1.7=h276745f_28
  - clangxx_osx-arm64=19.1.7=h07b0088_28
  - click=8.1.8=pyh707e725_0
  - click-default-group=1.2.4=pyhd8ed1ab_1
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - compiler-rt=19.1.7=h855ad52_1
  - compiler-rt_osx-arm64=19.1.7=he32a8d3_1
  - cons=0.4.7=pyhd8ed1ab_2
  - contourpy=1.3.1=py312hb23fbb9_0
  - cookiecutter=2.6.0=pyhd8ed1ab_1
  - cpython=3.12.11=py312hd8ed1ab_0
  - cryptography=44.0.1=py312hf9bd80e_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h60b93bd_7
  - datasette=0.65.2=pyhd8ed1ab_0
  - debugpy=1.8.12=py312hd8f9ff3_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - diff-match-patch=20241021=pyhd8ed1ab_1
  - dill=0.3.9=pyhd8ed1ab_1
  - docstring-to-markdown=0.15=pyhd8ed1ab_1
  - docutils=0.21.2=pyhd8ed1ab_1
  - epoxy=1.5.10=hc919400_2
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - etuples=0.3.10=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - exchange-calendars=4.8=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - filelock=3.18.0=pyhd8ed1ab_0
  - flake8=7.1.2=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.56.0=py312h998013c_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.12.1=hadb7bae_2
  - fribidi=1.0.16=hc919400_0
  - frozendict=2.4.6=py312h0bf5046_0
  - frozenlist=1.5.0=py312h998013c_1
  - fzf=0.60.3=h8842463_0
  - gdk-pixbuf=2.42.12=h7ddc832_0
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - git=2.49.0=pl5321hd71a902_0
  - git-filter-repo=2.38.0=pyhd8ed1ab_1
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glib=2.82.2=heee381b_1
  - glib-tools=2.82.2=h1dc7a0c_1
  - glog=0.7.1=heb240a5_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.1.5=py312h524cf62_3
  - google-auth=2.38.0=pyhd8ed1ab_0
  - google-auth-oauthlib=1.2.1=pyhd8ed1ab_1
  - graphite2=1.3.14=hec049ff_2
  - graphviz=12.2.1=hff64154_1
  - greenlet=3.2.1=py312hd8f9ff3_0
  - gspread=5.12.4=pyh1a96a4e_0
  - gst-plugins-base=1.24.7=hb49d354_0
  - gstreamer=1.24.7=hc3f5269_0
  - gtk3=3.24.43=he7bb075_4
  - gts=0.7.6=he42f4ea_4
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5netcdf=1.7.3=pyhd8ed1ab_0
  - h5py=3.15.1=nompi_py312h4eecd6b_101
  - halo=0.0.31=pyhd8ed1ab_1
  - harfbuzz=10.4.0=hb72c1af_0
  - hdf5=1.14.6=nompi_he65715a_103
  - hicolor-icon-theme=0.17=hce30654_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - html5lib=1.1=pyhd8ed1ab_2
  - httpcore=1.0.9=pyh29332c3_0
  - httplib2=0.22.0=pyhd8ed1ab_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hupper=1.12.1=pyhd8ed1ab_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_1
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - inflection=0.5.1=pyhd8ed1ab_1
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh57ce528_0
  - ipympl=0.9.7=pyhcf101f3_2
  - ipython=8.34.0=pyh907856f_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - isort=6.0.1=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - janus=2.0.0=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=pyhd8ed1ab_2
  - jaraco.context=6.0.1=pyhd8ed1ab_0
  - jaraco.functools=4.1.0=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jellyfish=1.1.3=py312hcd83bfe_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - joblib=1.5.0=pyhd8ed1ab_0
  - json5=0.12.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py312h81bd7bf_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter-server-mathjax=0.2.6=pyhbbac1ac_2
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - keyring=25.6.0=pyh534df25_0
  - kiwisolver=1.4.8=py312h2c4a281_0
  - korean_lunar_calendar=0.3.1=pyhd8ed1ab_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - ld64=956.6=llvm19_1_he86490a_3
  - ld64_osx-arm64=956.6=llvm19_1_h6922315_3
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20250127.1=cxx17_h07bc746_0
  - libaec=1.1.4=h51d1e36_0
  - libarrow=20.0.0=h76b72fb_7_cpu
  - libarrow-acero=20.0.0=hf07054f_7_cpu
  - libarrow-dataset=20.0.0=hf07054f_7_cpu
  - libarrow-substrait=20.0.0=he749cb8_7_cpu
  - libblas=3.11.0=5_h8d724d3_accelerate
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.11.0=5_h752f6bc_accelerate
  - libclang-cpp17=17.0.6=default_hf90f093_8
  - libclang-cpp19.1=19.1.7=default_h73dfc95_5
  - libclang13=19.1.7=default_h81d93ff_2
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.14.1=h73640d1_0
  - libcxx=20.1.8=hf598326_1
  - libcxx-devel=19.1.7=h6dc3340_2
  - libcxx-headers=19.1.7=h707e725_2
  - libdeflate=1.23=hec38601_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libgcc=15.2.0=hcbb3090_16
  - libgd=2.3.3=hb2c3a21_11
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libglib=2.82.2=hdff4504_1
  - libgoogle-cloud=2.36.0=h9484b08_1
  - libgoogle-cloud-storage=2.36.0=h7081f7f_1
  - libgrpc=1.71.0=h857da87_1
  - libhwloc=2.11.2=default_hbce5d74_1001
  - libiconv=1.18=hfe07756_1
  - libintl=0.23.1=h493aca8_0
  - libintl-devel=0.23.1=h493aca8_0
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.11.0=5_hcb0d94e_accelerate
  - liblapacke=3.11.0=5_hbdd07e9_accelerate
  - libllvm17=17.0.6=hc4b4ae8_3
  - libllvm19=19.1.7=hc4b4ae8_1
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.64.0=h6d7220d_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h99b78c6_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopentelemetry-cpp=1.21.0=h0181452_0
  - libopentelemetry-cpp-headers=1.21.0=hce30654_0
  - libopus=1.3.1=h27ca646_1
  - libparquet=20.0.0=h636d7b7_7_cpu
  - libpng=1.6.47=h3783ad8_0
  - libpq=17.4=h6896619_0
  - libprotobuf=5.29.3=hccd9074_1
  - libre2-11=2024.07.02=hd41c47c_3
  - librsvg=2.58.4=h266df6f_2
  - libsigtool=0.1.3=h98dc951_0
  - libsodium=1.0.20=h99b78c6_0
  - libspatialindex=2.1.0=h57eeb1c_0
  - libsqlite=3.50.3=h4237e3c_1
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.21.0=h64651cc_0
  - libtiff=4.7.0=h551f018_3
  - libutf8proc=2.10.0=h74a6958_0
  - libuv=1.51.0=h6caf38d_1
  - libvorbis=1.3.7=h9f76cd9_0
  - libwebp=1.5.0=h1618228_0
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.6=h178c5d8_0
  - libxslt=1.1.39=h223e5b9_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=19.1.7=hdb05f8b_0
  - llvm-tools=19.1.7=hd2aecb6_1
  - llvm-tools-19=19.1.7=h87a4c7e_1
  - llvmlite=0.44.0=py312hc9b382d_2
  - log_symbols=0.0.14=pyhd8ed1ab_2
  - logical-unification=0.4.7=pyhd8ed1ab_0
  - lxml=5.3.1=py312h9535dd2_0
  - lz4-c=1.10.0=h286801f_1
  - macosx_deployment_target_osx-arm64=11.0=h6553868_4
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py312h998013c_1
  - matplotlib=3.10.1=py312h1f38498_0
  - matplotlib-base=3.10.1=py312hdbc7e53_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mergedeep=1.3.4=pyhd8ed1ab_1
  - minikanren=1.0.5=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - more-itertools=10.6.0=pyhd8ed1ab_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mplcursors=0.7=pyhd8ed1ab_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.1.0=py312hdb8e49c_1
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - multitasking=0.0.9=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_1
  - mysql-common=9.0.1=hd7719f6_4
  - mysql-connector-python=9.0.0=py312hde4cb15_1
  - mysql-libs=9.0.1=ha8be5b7_4
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hb482800_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbconvert-pandoc=7.16.6=hed9df3c_0
  - nbdime=4.0.2=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nbstripout=0.8.1=pyhd8ed1ab_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6.1=pyhcf101f3_0
  - nlohmann_json=3.12.0=ha1acc90_0
  - nodejs=24.4.1=hab9d20b_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nspr=4.36=h5833ebf_0
  - nss=3.108=ha3c76ea_0
  - numba=0.61.2=py312h32e2601_0
  - numpy=2.2.3=py312h7c1f314_0
  - numpydoc=1.8.0=pyhd8ed1ab_1
  - oauth2client=4.1.3=pyhd8ed1ab_1
  - oauthlib=3.2.2=pyhd8ed1ab_1
  - openblas=0.3.30=openmp_hea878ba_3
  - openjpeg=2.5.3=h8a3d83b_0
  - openldap=2.6.9=hbe55e7a_0
  - openpyxl=3.1.5=py312h4fb2c50_2
  - openssl=3.6.1=hd24854e_1
  - orc=2.1.2=hd90e43c_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.3.1=py312h98f7732_0
  - pandas_market_calendars=4.6.1=pyha770c72_0
  - pandoc=3.8.2=hce30654_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.2=h73f1e88_0
  - parquet-tools=0.2.16=pyhd8ed1ab_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pathspec=0.12.1=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=h297a79d_2
  - peewee=3.17.9=py312hef9ee69_0
  - perl=5.32.1=7_h4614cfb_perl5
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py312h50aef2c_0
  - pip=25.1.1=pyh8b19718_0
  - pipdeptree=2.26.1=pyhd8ed1ab_0
  - pixman=0.46.4=h81086ad_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - playwright=1.55.1=h63323fe_0
  - pluggy=1.5.0=pyhd8ed1ab_1
  - ply=3.11=pyhd8ed1ab_3
  - polars=1.32.3=default_h1fdcfb2_0
  - polars-default=1.32.3=py39h31c57e4_0
  - polygon-api-client=1.14.4=pyhd8ed1ab_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prometheus_client=0.22.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - propcache=0.2.1=py312h998013c_1
  - psutil=7.0.0=py312hea69d52_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=20.0.0=py312h1f38498_0
  - pyarrow-core=20.0.0=py312hc40f475_0_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.1=pyhd8ed1ab_1
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygithub=2.6.1=pyhd8ed1ab_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pylint=3.3.5=pyh29332c3_0
  - pylint-venv=3.0.4=pyhd8ed1ab_1
  - pyls-spyder=0.4.0=pyhd8ed1ab_1
  - pyluach=2.2.0=pyhd8ed1ab_1
  - pymc=5.27.0=h697028f_0
  - pymc-base=5.27.0=pyhcf101f3_0
  - pymysql=1.1.1=pyhd8ed1ab_1
  - pynacl=1.5.0=py312h024a12e_4
  - pyobjc-core=11.0=py312hb9d441b_0
  - pyobjc-framework-cocoa=11.0=py312hb9d441b_0
  - pyobjc-framework-coreservices=11.0=py312hea69d52_0
  - pyobjc-framework-fsevents=11.0=py312h81bd7bf_0
  - pyopenssl=25.0.0=pyhd8ed1ab_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pyqt=5.15.9=py312h550cae4_5
  - pyqt5-sip=12.12.2=py312h9f69965_5
  - pyqtwebengine=5.15.9=py312h14105d7_5
  - pysocks=1.7.1=pyha55dd90_7
  - pytensor=2.36.2=py312h93e161d_0
  - pytensor-base=2.36.2=np2py312h60fbb24_0
  - pytest=8.3.4=pyhd8ed1ab_1
  - python=3.12.11=hc22306f_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-gil=3.12.11=hd8ed1ab_0
  - python-graphviz=0.21=pyhbacfb6d_0
  - python-gssapi=1.9.0=py312h97903a5_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-lsp-black=2.0.0=pyhff2d567_1
  - python-lsp-jsonrpc=1.1.2=pyhff2d567_1
  - python-lsp-server=1.12.2=pyhff2d567_0
  - python-lsp-server-base=1.12.2=pyhd8ed1ab_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python.app=1.4=py312h830b0dc_4
  - python_abi=3.12=8_cp312
  - pytoolconfig=1.2.5=pyhd8ed1ab_1
  - pytorch=2.2.2=py3.12_0
  - pytz=2024.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyuca=1.2=pyhd8ed1ab_2
  - pyxdg=0.28=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h998013c_2
  - pyzmq=26.2.1=py312hf4875e0_0
  - qdarkstyle=3.2.3=pyhd8ed1ab_1
  - qhull=2020.2=h420ef59_5
  - qstylizer=0.2.4=pyhff2d567_0
  - qt-main=5.15.15=h67564f6_2
  - qt-webengine=5.15.15=h5422c0a_1
  - qtawesome=1.3.1=pyh9208f05_1
  - qtconsole=5.6.1=pyhd8ed1ab_1
  - qtconsole-base=5.6.1=pyha770c72_1
  - qtpy=2.4.3=pyhd8ed1ab_0
  - re2=2024.07.02=h6589ca4_3
  - readline=8.2=h1d1bf99_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - responses=0.25.6=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=14.2.0=pyhcf101f3_0
  - roman-numerals-py=3.1.0=pyhd8ed1ab_0
  - rope=1.13.0=pyhd8ed1ab_1
  - rpds-py=0.23.1=py312hd60eec9_0
  - rsa=4.9=pyhd8ed1ab_1
  - rtree=1.4.0=pyh11ca60a_1
  - s3transfer=0.13.0=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py312h79e0ffc_0
  - scipy=1.16.3=py312h39258fd_2
  - sdkroot_env_osx-arm64=14.5=hfa17104_3
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=80.9.0=pyhff2d567_0
  - shap=0.48.0=cpu_py312h49bd6d6_1
  - sigtool-codesign=0.1.3=h98dc951_0
  - sip=6.8.6=py312hd8f9ff3_2
  - six=1.17.0=pyhd8ed1ab_0
  - slicer=0.0.8=pyhd8ed1ab_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.1=h98b9ce2_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - sphinx=8.2.3=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - spinners=0.0.24=pyhd8ed1ab_1
  - spyder=6.0.4=hd8ed1ab_1
  - spyder-base=6.0.4=osx_pyh1a5313d_1
  - spyder-kernels=3.0.3=unix_pyh707e725_0
  - sqlalchemy=2.0.40=py312hea69d52_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py312ha11c99a_0
  - superqt=0.7.2=pyhb6d5dde_0
  - sympy=1.13.3=pyh2585a3b_105
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tapi=1600.0.11.8=h997e182_0
  - tbb=2021.13.0=h8149167_1
  - termcolor=3.1.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh31c8845_0
  - text-unidecode=1.3=pyhd8ed1ab_2
  - textdistance=4.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - three-merge=0.1.1=pyhd8ed1ab_1
  - thrift=0.20.0=py312hde4cb15_1
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_2
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tomlkit=0.13.2=pyha770c72_1
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.4.2=py312hea69d52_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - types-pyyaml=6.0.12.20241230=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - ujson=5.10.0=py312hde4cb15_1
  - unicodedata2=16.0.0=py312hea69d52_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=1.26.19=pyhd8ed1ab_0
  - uvicorn=0.38.0=pyh31011fe_0
  - visidata=3.3=pyhd8ed1ab_0
  - watchdog=6.0.0=py312hea69d52_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - websockets=12.0=py312he37b823_0
  - whatthepatch=1.0.7=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - wrapt=1.17.2=py312hea69d52_0
  - wurlitzer=3.1.1=pyhd8ed1ab_1
  - xarray=2025.12.0=pyhcf101f3_0
  - xarray-einstats=0.9.1=pyhd8ed1ab_0
  - xlrd=2.0.2=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - yaml=0.2.5=h3422bc3_2
  - yapf=0.43.0=pyhd8ed1ab_1
  - yarl=1.18.3=py312h998013c_1
  - yfinance=0.2.54=pyhd8ed1ab_0
  - zeromq=4.3.5=hc1bb282_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=h8359307_2
  - zstandard=0.23.0=py312hea69d52_2
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - datasette-cluster-map==0.18.2
      - datasette-leaflet==0.2.2
      - datasette-parquet==0.6.1
      - datasette-vega==0.6.2
      - duckdb==1.4.1
      - py-lets-be-rational==1.0.1
      - py-vollib==1.0.1
      - simplejson==3.20.1
      - sqlglot==27.29.0
prefix: /opt/anaconda3/envs/finance
